### ISSUE TITLE
[Feature Request] Put the progress bar somewhere in the main window instead of in a pop up

### ISSUE THREAD

**Issue by mhogomchungu** [JaGoLi/ytdl-gui#1]
Nothing to add here since the header has all the information.

**Comment by JaGoLi** [comment]
I personally think the progress window needs to be reworked too. My proposed solution would rather be to enable a user to minimze it. so that then you can have multiple downloads at once.

**Comment by JaGoLi** [comment]
Minimize option in beta branch.
