### ISSUE TITLE
Change options arrangement

### ISSUE THREAD

**Issue by humdingerb** [JaGoLi/ytdl-gui#10]
I think the GUI may look nicer if pop-up menus were used for the quality and format options. It'll make the GUI nicely compact.

Or, if you prefer not having the items "hidden" in a pop-up menu, arrange the radio buttons for quality and format vertically, i.e. in two columns.

**Comment by JaGoLi** [comment]
You can maybe develop a concept for your layout idea, but as of now my focus is on adding features such as playlist support and concurrent downloads. I will be closing this issue.

**Comment by humdingerb** [comment]
You could set a minimal window width. Relabel "Enter URL:" to "URL:" to save a wee bit of space. :)

Also, the text fields are almost never used to enter text by hand, I bet. People only click in the URL field to set focus to paste the URL they copied, and the destination path is probably only filled via the file dialog after clicking the "Browse..." button.

**Comment by humdingerb** [comment]
Here's a mockup:
![Mockup](https://i.postimg.cc/qMKmxTCQ/ytdl-mockup.png)

**Comment by JaGoLi** [comment]
Thank you. Having seen the mock-up I think there is too much whitespace. You are essentially trading horizontal space for vertical space. There are other issues of greater importance that I need to work on. I appreciate your efforts to port my application to haiku os, however I fail to see how this is beneficial sorry.

**Comment by humdingerb** [comment]
Alright, I don't want to waste more of your time. A few last thoughts though:
The eye browses vertically listed items much faster than horizontally. Horizontal radio buttons are rarely seen for more than 2 items.
The text boxes could be quite a bit smaller, making the window narrower and eliminating the bit excessive whitespace.

Maybe you come back to the GUI design, after implementing the more important features (which may need options in the GUI themselves) and remember this mockup for inspiration. :)
Thanks.

**Comment by JaGoLi** [comment]
I see what you mean now. I don't see the need to arrange the items vertically though. In future versions I will put the radio buttons a bit closer together because you are right that my app is a bit too wide.
