### ISSUE TITLE
Support for --referer parameter

### ISSUE THREAD

**Issue by AlexFolland** [JaGoLi/ytdl-gui#11]
`youtube-dl` has a `--referer` parameter which is necessary to download videos from some websites.  It accepts a URL.

Here's the description from `youtube-dl --help`:

```
--referer URL                    Specify a custom referer, use if the video
                                     access is restricted to one domain
```

**Comment by JaGoLi** [comment]
Can you give me an example where the refer switch is used? I don't fully get what they mean by custom referer.

**Comment by JaGoLi** [comment]
After having done more research, this requires the user to add a second url to the command and is only useful for embedded videos on another website. This is a bit clunky to implement in a gui and it's an option that won't be used enough for me to want to implement it.

**Comment by AlexFolland** [comment]
> Can you give me an example where the refer switch is used? I don't fully get what they mean by custom referer.

An example is a site which requires the `--referer` to have the same URL as the video page, so the same URL appears twice in the command line to download.

Clunkier is having to copy the URL twice into the `youtube-dl` command line and use the terminal.

**Comment by JaGoLi** [comment]
Good point, it may be of some more use than I originally thought. I will think about adding it in the future. It is still low in my list of priorities, sorry.

**Comment by AlexFolland** [comment]
I understand.  Thank you for your tool and your consideration.
