### ISSUE TITLE
Missing repository for bionic

### ISSUE THREAD

**Issue by theniwo** [JaGoLi/ytdl-gui#12]
On http://ppa.launchpad.net/mordec13/youtubedl-gui/ubuntu/dists/ I see only devel focal groovy and xenial
Would you please add bionic 18.04? It is still a very common release.
Thanks

**Comment by JaGoLi** [comment]
Xenial was just for a test. I don't have any packages for it and won't be having any in the future. I tried adding support for bionic, but I couldn't get it to build on the ubuntu servers. If you really want to add support, please give me a list of dependencies for building on ubuntu 18,04 because I can't get it to work after having tried multiple fixes. I will close this issue for now. If you can get it to work, please comment on this and I may reopen it when it works.

**Comment by theniwo** [comment]
These are the dependencies I installed according to your readme
```
ii  build-essential             12.4ubuntu1        amd64              Informational list of build-essential packages
ii  ffmpeg                      7:3.4.8-0ubuntu0.2 amd64              Tools for transcoding, streaming and playing of multimedia f
ii  qt5-default:amd64           5.9.5+dfsg-0ubuntu amd64              Qt 5 development defaults package
ii  qtdeclarative5-dev:amd64    5.9.5-0ubuntu1.1   amd64              Qt 5 declarative development files
```
Build was find. One warning:
```

mainactions.cpp: In member function ‘void ytdl::killDownloadProcess()’:
mainactions.cpp:101:16: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
     std::system("killall youtube-dl");
     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by JaGoLi** [comment]
I see you tried out the beta branch of which I pushed changes to last night. What I meant by dependencies is that you have to build in a completely clean system on canonical's servers and there I was getting build errors. The warning (not error) you see on your system is perfectly normal and happens on all systems, I am implementing a way to stop the download, that function returns an int, but I am not doing anything with it, so it throws a warning.

**Comment by JaGoLi** [comment]
Sorry, my bad this warning also occurs also in the stable branch. It's not critical as explained, but I will be providing fixes for it and looking into a package for ubuntu bionic.

**Comment by JaGoLi** [comment]
Good news! I was able to fix the build issue by changing the makefile for ubuntu 18.04. This means that the version number has to be different because the source has changed. However, the code is still the same. You should now see youtubedl-gui verison 0.8 in the ubuntu repository for bionic.
