### ISSUE TITLE
Haiku build fails to download

### ISSUE THREAD

**Issue by Begasus** [JaGoLi/ytdl-gui#13]
Some is writing up a recipe for this to work on Haiku (https://www.haiku-os.org) at https://github.com/haikuports/haikuports/pull/5617

Running this in Terminal reveals the error:
```
Support for the -P option is not compiled into this --disable-perl-regexp binary
```

Looking at the source I removed the "P" option for grep in line: https://github.com/JaGoLi/ytdl-gui/blob/927f129a4613d27f3dc7f3cc98fd71e3e3199798/src/mainactions.cpp#L122

```diff
-    std::string parse_output = R"(stdbuf -o0 grep -oP '^\[download\].*?\K([0-9]+)' | tee /tmp/ytdl_prg)";
+    std::string parse_output = R"(stdbuf -o0 grep -o '^\[download\].*?\K([0-9]+)' | tee /tmp/ytdl_prg)";
```

This worked for me and I was able to download a Video and Sound file.

**Comment by JaGoLi** [comment]
Looks quite promising! I will be pushing this commit to the beta branch. If this doesn't add any issues it will be standard because it increases compatibility with macOS too.

**Comment by JaGoLi** [comment]
Upon testing, removing the P option breaks the progress bar in linux. The progress of the download keeps on being stuck at zero. I have to discard this change for now. Can you get gnu grep to work on haiku?

**Comment by Begasus** [comment]
> Upon testing, removing the P option breaks the progress bar in linux

Yeah, saw the same thing here, we've got grep on Haiku, maybe some changes are needed there to fix this, thanks for looking into this :+1:

**Comment by Begasus** [comment]
Just a short notice, after doing some changes to our grep port this is working fine ;)
![youtubedl-gui](https://user-images.githubusercontent.com/16057090/105361987-9e41dc00-5bfa-11eb-8f22-8a79e792a1e1.png)

**Comment by JaGoLi** [comment]
Looking great! Thank you for your contributions. It's great to see the application running on another os! I'm almost done adding support for playlists and the ability to properly cancel downloads. If you have any commits to suggest in the future, please request them through the beta branch. There you can also get a preview of the changes so you can test the app before pushing it out to the haiku userbase.

**Comment by Begasus** [comment]
One thing maybe, but not sure if I would file a new issue for this, I can download from Youtube, but it downloads the video and audio in separate files, looking at the video then it doesn't see any audio track?

**Comment by JaGoLi** [comment]
Ok, it's probably because you may not have ffmpeg running correctly on haiku. Make sure ffmpeg is installed and working. This issue doesn't seem to occur on linux, and therefore I will not open an issue.

**Comment by Begasus** [comment]
Audio file is saved ok, is it a deppendency to this?

**Comment by JaGoLi** [comment]
ffmpeg is an optional dependency to youtubedl, but it is required for my gui because it does some reencoding. I tried on linux and can't get the issue to appear. Can you send me a link where the issue occurs on your os?

**Comment by Begasus** [comment]
It's a bit busy atm, shipped a pup yesterday to the states, on the other hand we got word that one of our pups got her first litter and still in labour, let me look again and I'll get back to you :)

**Comment by JaGoLi** [comment]
That's perfectly acceptable! :) Anyways, if you were to look at the commit history on this repo for the last few days you would see that there's quite a bit of changes going on, so it's probably not the best time to be debugging on haiku. I do my testing on linux as you see, I'm very unfamiliar with the os and I don't know what would case breakages.
