### ISSUE TITLE
Audio tab

### ISSUE THREAD

**Issue by Begasus** [JaGoLi/ytdl-gui#17]
Downloaded a playlist link from youtube with the correct url, when using the audio tab and select download (after checked "playlist") it only downloads the first track, if I select video tab it downloads the full list of files?
How would I go about it to only download the audio tracks?
**EDIT** this was done with a build from the beta branch checkout :)

**Comment by JaGoLi** [comment]
Thank you very much for trying this out. This is why I have a beta branch, some features may not be final. :) I personally tried downloading a music album from youtube with the playlist check and it worked really well. What os/distro are you using, and do you have ffmpeg on your system? Currently, the audio tab re-encodes files using ffmpeg, so if there is a problem with it, the whole process may stop. I am also working on an option check to bypass all settings and use the defaults suggested by youtube-dl so users can choose to avoid re-encoding.

**Comment by Begasus** [comment]
Main OS on trying this out is still Haiku ;)
It works very well so far, only issue so far I have for downloading is the separate files (video/audio), having a playlist to download works fine otherwise, beta is not scaring me, it's called development/progress :)
We do have ffmpeg (and it's installed), if I use the cmd: youtube-dl it works well, on single of playlist file(s)

**Comment by JaGoLi** [comment]
I think this may be a bug with downstream youtube-dl on haiku. When using the audio tab, I am using the flag "--audio-format" check to see if the flag works correctly on haiku.

**Comment by Begasus** [comment]
Seems to be ok:
```
~/Desktop> youtube-dl --audio-format=mp3 https://youtu.be/U86okxevw4w
[youtube] U86okxevw4w: Downloading webpage
[download] Destination: Suki & Matti pups playing with big sister Fire  -)-U86okxevw4w.mp4
[download] 100% of 38.03MiB in 00:25
```

**Comment by JaGoLi** [comment]
Does the end result give you an mp3 though? Please check that.

**Comment by Begasus** [comment]
No mp3 file, only the mp4 file

**Comment by JaGoLi** [comment]
Exactly as I suspected. On linux you would be left with only an mp3 file. There is an issue with youtube-dl and ffmpeg. Do you have ffmpeg on your system?

**Comment by Begasus** [comment]
ffmpeg is installed on my system yes (we're pretty much on par on those things) ;)
The link used in there is a video with sound though, so I would suspect 1 file including both audio and video?

**Comment by JaGoLi** [comment]
Just to make sure I tried downloading the whole Boston album on an arch linux virtual machine with a clean system and kde plasma, and it worked fine. I ended up with only mp3s of the songs in high quality. This is really an issue with haiku os so I will have to close it.

**Comment by Begasus** [comment]
Fixed it locally :)

**Comment by JaGoLi** [comment]
What was the fix?

**Comment by Begasus** [comment]
Still looking into it a bit, but it seems it needs the "cmd:ffmpeg" not just the libraries

**Comment by Begasus** [comment]
For audio this is working fine already :) 
![youtube-dl-gui](https://user-images.githubusercontent.com/16057090/105514995-73c45180-5cd4-11eb-8cea-75ffa157cf10.png)

**Comment by Begasus** [comment]
And some more progress (won't bother you again before some real issues pop up) ;)
![youtube-dl-gui](https://user-images.githubusercontent.com/16057090/105530683-65803080-5ce8-11eb-9fb8-3eff322b28c6.png)

**Comment by JaGoLi** [comment]
I'm going to merge the beta with main this evening. I think you have sorted out the issues on haiku for it to be stable enough for use. Am I right?

**Comment by Begasus** [comment]
> I think you have sorted out the issues on haiku for it to be stable enough for use.

Yes, most of the issues I'm facing are not related to the code here, some fine-tuning still remains, but that is something to deal with later (eg dependencies ...)
