### ISSUE TITLE
Add option to download subtitles

### ISSUE THREAD

**Issue by Begasus** [JaGoLi/ytdl-gui#21]
Made a small change in the source (added "--all-subs" to the download video section) and was able to download the included subtitles for a movie (in this one there were 2 different languages with the subtitles)
Maybe a checkbox could be added for this?

**Comment by JaGoLi** [comment]
Good idea, I added "--all-subs" to the default command because it doesn't do anything to audio files. It should be the default option anyway. Thank you for your suggestion.
