### ISSUE TITLE
When Hirsute (21.04) version will be out?

### ISSUE THREAD

**Issue by twisthead** [JaGoLi/ytdl-gui#31]
Hello, I was installing ytdl on the latest release of ubuntu and I can't because the PPA doesn't had any release file. Please release it for 21.04.

**Comment by JaGoLi** [comment]
Hi,
Thank you for reminding me to create a new release for Ubuntu 21.04. I will have an update available by the end of the day.

**Comment by JaGoLi** [comment]
I have uploaded new packages for ubuntu hirsute. You should be able to install it now. Enjoy!

**Comment by twisthead** [comment]
thank you very much you are best. thanks very much again.
