### ISSUE TITLE
drop StartupWMCLass from desktop file

### ISSUE THREAD

**Issue by advaithm** [JaGoLi/ytdl-gui#34]
including the `StartupWMCLass` key in the .desktop file will result in appstream not generating metadata from it. appstream data is useful for different package managers such as the Gnome store or Kde's discover. This is a too big of a issue since it can be removed but it would be better if downstream did not need to mess with the desktop file

**Comment by JaGoLi** [comment]
Ok, I tired the change in a vm and it doesn't seem to break anything. I will merge your commit.
