### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by barak** [JaGoLi/ytdl-gui#37]
This is really an upstream issue, but apparently Rogério T. Brito, who maintains youtube-dl, recently died of Covid-19.

**Comment by toushin-taishi** [comment]
So sad and sorry to hear this :-(

**Comment by JaGoLi** [comment]
It is so sad, I'm at a loss for words. What should we do? Who will maintain the project? My condolences go out to his family and the people who knew him.

**Comment by advaithm** [comment]
I believe there are a lot of people are there who can maintain it, we just have to see who steps up or which fork gets "blessed"

**Comment by JaGoLi** [comment]
I guess there's nothing relevant that can be added at this point even though it's quite sad. I think it's better to close the issue.
