### ISSUE TITLE
Failed! Recheck Input for Errors

### ISSUE THREAD

**Issue by NayamAmarshe** [JaGoLi/ytdl-gui#38]
I'm trying to download this:
https://www.youtube.com/watch?v=XTN_-pRZjoU

I've selected Audio - Best - MP3, the checkboxes are all unchecked but whenever I press download it says: Failed! Recheck Input for Errors. This error seems to appear on multiple videos.

**Comment by JaGoLi** [comment]
Does this happen on all videos you have tried or only this one?

**Comment by JaGoLi** [comment]
Ok, I see what is happening. You need to install `youtube-dl` via `pip`.
For the application to work on your system do:
`sudo pip3 install youtube-dl`
It should work then.

**Comment by NayamAmarshe** [comment]
> Ok, I see what is happening. You need to install `youtube-dl` via `pip`.
> For the application to work on your system do:
> `sudo pip3 install youtube-dl`
> It should work then.

Ah! I must have missed that part, Thanks!
