### ISSUE TITLE
option to download/embed thumbnail 

### ISSUE THREAD

**Issue by advaithm** [JaGoLi/ytdl-gui#39]
`youtube-dl` has an option to download and embed a thumbnail in the file. this is exposed with the `--embed-thumbnail` flag. it would be nice if this could be exposed to the user as a toggle

**Comment by JaGoLi** [comment]
I'm thinking about the best way to implement this. I don't want my app to have too many toggles. I want to keep it simple. I may just include it as default if it doesn't have adverse effects for people who don't care about thumbnails.

**Comment by advaithm** [comment]
it makes downloads a bit longer but it doesn't make a big difference

**Comment by JaGoLi** [comment]
I tried it out, and I can only enable it for audio and specifically mp3 format. My app prioritizes video resolution and not file format so I can't only select mp4. It does work reliably with mp3 and I have that set for default in beta branch.
