### ISSUE TITLE
[Feature Request] Download an entire playlist

### ISSUE THREAD

**Issue by kdav5758** [JaGoLi/ytdl-gui#4]
Instead of downloading a video one by one users might as well create playlists and download all the videos in that given playlist. If that's not possible, then add a `wget` like feature to download all the links in a given .txt file (`-i` flag in the case of `wget`). 

This will make life way more easier for people collecting videos for video production purposes that need extensive material for their projects.

Thanks in advance!

**Comment by JaGoLi** [comment]
Yes, I have gotten this feature request quite a bit, and I am working on implementing it seriously. My proposed way of doing so is inputting a text file with one youtube url per line. The app will then download one-by-one each url specified.

**Comment by emiliskvg** [comment]
youtube-dl supports playlists, you just need a correct YouTube link, like this one: **https://www.youtube.com/playlist?list=**

**Comment by JaGoLi** [comment]
As per your suggestion, the easiest solution was to use the built-in function of youtube-dl. I have added a checkbox to enable the downloading of youtube playlist links. If you enter a playlist url without checking the playlist button, it will still just download one video as before, you have to enable playlist for it to download the whole thing.
