### ISSUE TITLE
Building on Debian 10

### ISSUE THREAD

**Issue by nobodysu** [JaGoLi/ytdl-gui#40]
Only able to build after:
`# apt install cmake`
`$ cd ytdl-gui && cmake . && make`

Env: clean Debian 10 install:
```
$ uname -a
Linux debian 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by JaGoLi** [comment]
This is NOT an issue. I have changed the build system from make to cmake. I forgot to change the readme though.
