### ISSUE TITLE
python3-pip dependency is excessive in ppa

### ISSUE THREAD

**Issue by nobodysu** [JaGoLi/ytdl-gui#45]
youtube-dl could be acquired by other means and not everyone wants a whole toolchain (216 Mb) on their system.

**Comment by nobodysu** [comment]
`python`, however, is necessary.

```
$ youtube-dl --version
/usr/bin/env: python: No such file or directory
```

```
# apt install python
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python-is-python2' instead of 'python'
```

```
$ youtube-dl --version
2021.06.06
```

**Comment by JaGoLi** [comment]
I have instead decided to make the package conflict with the ubuntu repo's version of `youtube-dl` and maintain `python3-pip` as a dependency. As well, there is now a postinstall script installing `youtube-dl` via `pip-3` automatically. I think this is the best way for most users as it makes sure that they will be using an up-to-date and working version of `youtube-dl` when they install the program.
