### ISSUE TITLE
Feature request: save previously used settings

### ISSUE THREAD

**Issue by nobodysu** [JaGoLi/ytdl-gui#46]
What about saving last used settings somewhere in `@{HOME}/.config/youtube-dl/`?
Would be hugely convenient instead of clicking the same buttons every time.

**Comment by JaGoLi** [comment]
This is a good feature. I will be working on it in the coming days.
I haven't had the time recently to go through all requests, but I do now.

**Comment by JaGoLi** [comment]
The feature is now completed with error handling and all. It is now in the beta branch. 
I suggest you test it to see if there are any issues on your end. I will merge it into the main branch very soon.

**Comment by nobodysu** [comment]
Seems good on Debian 10, thank you for taking the time!
