### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by rubyFeedback** [JaGoLi/ytdl-gui#56]
I just did git clone, then compiled, all went fine when compiling it.

Starting the GUI worked fine too.

I tested via a youtube URL:

Youtube-dl command:  "youtube-dl 2> /tmp/ytdl_stderr --no-warnings --all-subs -x 'https://www.youtube.com/watch?v=s83LfYF1IRU' -o '/root/Downloads/%(title)s.%(ext)s' --audio-format mp3 --audio-quality 0 --ignore-config --no-playlist --embed-thumbnail --newline | stdbuf -o0 grep -oP '^\\[download\\].*?\\K([0-9]+)'"

This actually failed.

I got a pop-up message saything something about the command failing.

"Failed! Recheck input for errors" or something like that.

No idea about the errors.

But I have a few minor suggestions: could the error message be stored
in a back log? Right now it is a popup that disappears again so I had
to type the error message.

Also it would be useful if the error message is more verbose - perhaps
display the command that is failing at the moment you show the popup.

I don't know what fails or why; perhaps a second tab could be used
for error output or something like that. Right now I am a bit confused.

I'll give it some try at a later time again, so no worries - I understand
that good code takes proper time to engineer. Props for the effort,
there are not many GUIs for youtube-dl (this is actually one use case,
I want to try that on windows; on linux I can work with the commandline
+ ruby "scripting" just fine, but on windows I need all the help I can get,
even with WSL1 and WSL2, which is good, but not perfect...)

**Comment by rubyFeedback** [comment]
Oops, sorry about the title - my crappy palemoon browser does not make it easily possible to re-edit the title.

I meant "Download of a URL failed while using the ytdl-gui interface". I did NOT meant that the download
of the e. g. source code failed. Just to clarify that.

**Comment by JaGoLi** [comment]
Do you have `youtube-dl` on your system? You will need to install the lastest version using `pip3`.

**Comment by JaGoLi** [comment]
I don't have enough info to debug this. All I know is I have tested on all supported platforms and it works. I will close it for now.
