### ISSUE TITLE
looks only for youtube-dl which isn't included in solus os right out of the box. Instead uses youtube-dlc

### ISSUE THREAD

**Issue by diggajupadhyay** [JaGoLi/ytdl-gui#8]
https://github.com/JaGoLi/ytdl-gui/blob/538ed929d614ec8ff3cb7d7c8f38396f70469e37/src/mainactions.cpp#L119

**Comment by JaGoLi** [comment]
My application is designed to work with upstream youtube-dl and I will only support that version for now. Feel free to fork my application in order to maintain compatibility with the solus fork of youtube-dl by changing the code.
